select * from customer limit 20

-- Q1. What is the total revenue generated by male vs. female customers?

SELECT
    gender,
    SUM("purchase_amount_(usd)") AS revenue
FROM customer
GROUP BY gender;


-- Q2. Which customers used a discount but still spent more than the average purchase amount?
-- Q2. Customers who used a discount but still spent more than average

SELECT
    customer_id,
    "purchase_amount_(usd)" AS purchase_amount,
    discount_applied
FROM customer
WHERE discount_applied = 'Yes'
  AND "purchase_amount_(usd)" > (
      SELECT AVG("purchase_amount_(usd)")
      FROM customer
  );

-- Q3. Which are the top 5 products with the highest average review rating?

SELECT
    item_purchased,
    ROUND(AVG(review_rating::numeric), 2) AS average_rating
FROM customer
GROUP BY item_purchased
ORDER BY average_rating DESC
LIMIT 5;

-- Q4. Compare the average purchase amounts between Standard and Express shipping.

-- Q4. Compare the average purchase amounts between
-- Standard and Express shipping.

SELECT
    shipping_type,
    ROUND(AVG("purchase_amount_(usd)"), 2) AS average_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more?
-- Compare average spend and total revenue between subscribers and non-subscribers.

-- Q5. Do subscribed customers spend more?
-- Compare average spend and total revenue between
-- subscribers and non-subscribers.

SELECT
    subscription_status,
    COUNT(*) AS customer_count,
    ROUND(AVG("purchase_amount_(usd)"), 2) AS average_spend,
    SUM("purchase_amount_(usd)") AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY average_spend DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

-- Q6. Which 5 products have the highest percentage
-- of purchases with discounts applied?

SELECT
    item_purchased,
    COUNT(*) AS total_purchases,
    SUM(
        CASE
            WHEN discount_applied = 'Yes' THEN 1
            ELSE 0
        END
    ) AS discounted_purchases,
    ROUND(
        100.0 * SUM(
            CASE
                WHEN discount_applied = 'Yes' THEN 1
                ELSE 0
            END
        ) / COUNT(*),
        2
    ) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number
-- Q7. Segment customers into New, Returning, and Loyal
-- based on previous purchases.
-- of previous purchases, and show the count of each segment.

SELECT
    CASE
        WHEN previous_purchases <= 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 5 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM customer
GROUP BY customer_segment
ORDER BY customer_count DESC;




-- Q8. What are the top 3 most purchased products within each category?


WITH product_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(*) AS purchase_count
    FROM customer
    GROUP BY category, item_purchased
),
ranked_products AS (
    SELECT
        category,
        item_purchased,
        purchase_count,
        RANK() OVER (
            PARTITION BY category
            ORDER BY purchase_count DESC
        ) AS product_rank
    FROM product_counts
)
SELECT
    category,
    item_purchased,
    purchase_count
FROM ranked_products
WHERE product_rank <= 3
ORDER BY category, purchase_count DESC;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases)
-- also likely to subscribe?

SELECT subscription_status,
COUNT(customer_id) AS Repeat_Buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status
  

-- Q10. What is the revenue contribution of each age group?


SELECT
    age_group,
   
    SUM("purchase_amount_(usd)") AS total_revenue
    FROM customer
  
GROUP BY age_group

ORDER BY total_revenue DESC;